[project]
name = "2nd-rag-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zabih", email = "zabihattu217@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.141.1",
    "google-api-python-client>=2.201.0",
    "google-auth>=2.59.1",
    "google-auth-oauthlib>=1.5.0",
    "langchain>=1.4.2",
    "langchain-community>=0.4.2",
    "langchain-openai>=1.6.6",
    "pypdf>=6.19.0",
    "streamlit>=1.64.0",
    "supabase>=2.32.0",
]

[project.scripts]
2nd-rag-project = "2nd_rag_project:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
